#define USB_VBUS_PIN GP24
#define BACKLIGHT_PIN GP25
#define BACKLIGHT_LEVELS 8
#define BACKLIGHT_CAPS_LOCK
//#define BACKLIGHT_BREATHING
//#define BREATHING_PERIOD 3
#define BACKLIGHT_ON_STATE 1
#define BACKLIGHT_LIMIT_VAL 255
#define BACKLIGHT_DEFAULT_ON true
//#define BACKLIGHT_DEFAULT_BREATHING true

